name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: etido-tdd-recap
  ECS_SERVICE: etido-tdd-recap-363a
  ECS_CLUSTER: etido-tdd-cluster
  EXECUTION_ROLE_ARN: arn:aws:iam::261219435789:role/service-role/ecsTaskExecutionRole
  INFRASTRUCTURE_ROLE_ARN: arn:aws:iam::261219435789:role/ecsInfrastructureRoleForExpressServices

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install browser
        run: playwright install chromium

      - name: Test code
        run: pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::261219435789:role/EtidoTddRecapRole

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to Amazon ECS Express Mode
        uses: aws-actions/amazon-ecs-deploy-express-service@v1
        with:
          cluster: ${{ env.ECS_CLUSTER }}
          service-name: ${{ env.ECS_SERVICE }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          execution-role-arn: ${{ env.EXECUTION_ROLE_ARN }}
          infrastructure-role-arn: ${{ env.INFRASTRUCTURE_ROLE_ARN }}